Update issue templates
SPLUG-GIT/project pull request #16
Opened 2020-09-28 14:02 UTC by DAEHOCHANG

2020-10-05 13:22 UTC, always0ne approved these changes

2020-10-06 04:24 UTC, always0ne reviewed
이 부분은 검토해주셨으면 좋겠습니다.

2020-10-06 04:24 UTC, always0ne commented on .github/ISSUE_TEMPLATE/feature-request.md
> +title: "[Suggestion Feature]"
너무 길어요

2020-10-06 04:25 UTC, always0ne requested changes

2020-10-06 04:25 UTC, always0ne commented on .github/ISSUE_TEMPLATE/feature-request.md
> +## If you choice ETC, Your suggestions
더 많은 가지수 필요? 혹은 삭제

2020-10-06 04:31 UTC, DAEHOCHANG commented on .github/ISSUE_TEMPLATE/feature-request.md
> +## If you choice ETC, Your suggestions
해써

2020-10-06 04:31 UTC, always0ne approved these changes
오키

2020-10-06 04:32 UTC, merged